name: Quadratic Equation Test
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.0-rc.1'
      - name: Setu Up Coverage
        run: |
          pip install genbadge[coverage]
      - name: Test with pytest
        run: |
          pip install pytest pytest-cov
          pytest test_main.py --doctest-modules --junitxml=junit/test-results.xml --cov=com --cov-report=xml --cov-report=html
          genbadge coverage xml
          genbadge coverage
